server:
  port: 8084

spring:
  application:
    name: s-lusambo

  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: s-lusambo
      authentication-database: admin
      port: 27017